### ISSUE TITLE
It seems to have a bug in the file quantDmcKLmeans.m?

### ISSUE THREAD

**Issue by ze-ta** [Lcrypto/Density-Evolution-AWGN#1]
means = seed(pxgy,K);

what does this mean? Matlab seems do not have this function ``seed".

**Comment by Lcrypto** [comment]
Just comment 
means = seed(pxgy,K);
and uncomment upper code 
% Random mean initialization
 sample = randperm(M);
 means  = zeros(K,J);
 for i = 1:K
     means(i,:) = pxgy(sample(i),:);
 end 
Thank you!
